# Generated by Django 3.0.2 on 2020-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkside', '0004_resulttesttwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttesttwo',
            name='question',
            field=models.CharField(default='', max_length=500),
        ),
    ]
