# Generated by Django 3.0.2 on 2020-05-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkside', '0005_resulttesttwo_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulttesttwo',
            name='choise',
            field=models.CharField(default='', max_length=50, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='resulttesttwo',
            name='question',
            field=models.CharField(default='', max_length=500, verbose_name='Вопрос'),
        ),
    ]
