# Generated by Django 3.0.2 on 2020-05-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darkside', '0006_auto_20200525_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resulttest',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.RemoveField(
            model_name='resulttest',
            name='result',
        ),
        migrations.AddField(
            model_name='resulttest',
            name='choise',
            field=models.CharField(default='', max_length=50, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='resulttest',
            name='question',
            field=models.CharField(default='', max_length=500, verbose_name='Вопрос'),
        ),
        migrations.DeleteModel(
            name='ResultTestTwo',
        ),
    ]
